name: Build and Test Classic .NET Framework Project

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore NuGet packages
      run: nuget restore UnitTestPro2_GitHubActions.sln  

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build the project
      run: msbuild UnitTestPro2_GitHubActions.sln /p:Configuration=Release

    - name: Run Selenium Tests
      run: vstest.console.exe F:\Practice_Final\SeleniumWithC#_GitHub\UnitTestPro2_GitHubActions\UnitTestPro2_GitHubActions\bin\Debug\UnitTestPro2_GitHubActions.dll --configuration Release

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-*.xml'  